### ISSUE TITLE
Api Sales_shipment_lines is not created after closing the sales order.

### ISSUE THREAD

**Issue by Andre-Samsa** [SamsaSoftware/samsa_docs#4]
Test to convert to issue

**Comment by relitodea** [comment]
issue is fixed - bug solved - Pallets have now a is_booked status so double booking is not possible

**Comment by Andre-Samsa** [comment]
Lines come through now. Bottle pallets are ok. Sending 1 box caps works, multiple boxes give an error and are not send to Nav.

**Comment by Andre-Samsa** [comment]
Bottle pallets are ok. Sending 1 box caps works, multiple boxes give an error and are not send to Nav.

**Comment by Andre-Samsa** [comment]
Tested again with order VO2100069, still not working. Same problems and part of the problem is that no Sales_Shipments is created, it does try to make the lines, but no header.

**Comment by Andre-Samsa** [comment]
Test completed, posting is OK.
